### ISSUE TITLE
add .forEach, .map and .filter

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-base#125]
maybe nice to have

- [ ] each (remove return functionality) -- no just add forEach
- [ ] map
- [ ] filter
- [ ] reduce
- [ ] push

**Comment by jimdebeer** [comment]
is this something we want? its basically replace

`
base.keys().map[(key => base[key]).map()
`

with
`
base.map()
`

**Comment by nfrade** [comment]
+1 for sure!

**Comment by jimdebeer** [comment]
.forEach as well?

**Comment by nfrade** [comment]
Well its syntax sugar right?

**Comment by jimdebeer** [comment]
uh no each has a special extra thing that when you return for it breaks a loop - which is really annoying with es6 shorthand notation

**Comment by jimdebeer** [comment]
so im making a new major version and can change this now

**Comment by jimdebeer** [comment]
also add reduce why not

**Comment by jimdebeer** [comment]
.each remove return behvaiour

**Comment by jimdebeer** [comment]
actually like the idea of adding push that just generates time stamp + potentially a src id (for hub)

**Comment by nfrade** [comment]
.push() instead of a set?

**Comment by jimdebeer** [comment]
no generates a new key

**Comment by nfrade** [comment]
Ahhh I see. sounds good. Goes away from the way we usually work. But may be a good alternative

**Comment by jimdebeer** [comment]
maybe replace each with every and some (similar apis)
