### ISSUE TITLE
"compute" in string notation

### ISSUE THREAD

**Issue by nfrade** [vigour-io/brisky-base#128]
I remember seeing something like `state.get('something.compute', false)`
Is this a shorthand for `state.get('something', false).compute()`?
I tried a bit but if the path did not exist I got an error not being able to create the property _compute_.

**Comment by jimdebeer** [comment]
when you call methods you cant have a default

 state.get('something.compute') works
 state.get('something.compute', false) does not

**Comment by jimdebeer** [comment]
we could make something for it bit difficult when you chain over methods

**Comment by nfrade** [comment]
What does it return when the path does not exist?
Well if you need defaults just use with `.compute()`

**Comment by jimdebeer** [comment]
yeah i geuss so
